### PR TITLE
fix vector angle calculation error

### PR DESCRIPTION
**Pull request by Xuefeng-Zhu**
image

It seems that vector angle calculation is not correct

### CODE REVIEW

**Comment by mateogianolio** [comment]
Great catch!  I will merge immediately and push the patch to npm. Thank you.

**Comment by ahvonenj** [comment]
Using vectorious 4.3.2, is this result caused by this issue?:

**Comment by Xuefeng-Zhu** [comment]
@ahvonenj Your issue is caused by the bug fixed in this PR. The fix has been included in 4.3.3, so please upgrade to latest version

**Comment by mateogianolio** [comment]
Seems like I forgot to push 4.3.3 to npm, will fix in a few mins!

**Comment by mateogianolio** [comment]
Done.

**Pull request merged**
