### PR TITLE
Vectorious 2.0.0

### PR DESCRIPTION
**Pull request by mateogianolio**
```1.1.6``` to ```2.0.0```

* **Additions:**
    * [Travis CI](https://travis-ci.org/mateogianolio/vectorious)
    * Complete **mocha** testing suite
    * ```Matrix.inverse()```
    * Static methods:
        * ```Vector.add(a, b)```
        * ```Vector.subtract(a, b)```
        * ```Vector.dot(a, b)```
        * ```Vector.angle(a, b)```
        * ```Vector.project(a, b)```
        * ```Vector.equals(a, b)```
        * ```Vector.combine(a, b)```
        * ```Matrix.add(a, b)```
        * ```Matrix.subtract(a, b)```
        * ```Matrix.multiply(a, b)```
        * ```Matrix.augment(a, b)```
        * ```Matrix.equals(a, b)```
* **Modifications:**
    * Bug fixes
    * Speed increases
    * Improved ```README.md``` with links to Wikipedia for various Vector and Matrix operations 
    * ```Vector.zeros```, ```Vector.ones```, ```Vector.range```, ```Matrix.identity```, ```Matrix.zeros``` and ```Matrix.ones``` converted to static methods.

### CODE REVIEW

**Comment by metabench** [comment]
It's worth mentioning the speed increases in the changelog.

**Comment by mateogianolio** [comment]
Are you OK with releasing 2.0.0 now?

**Comment by metabench** [comment]
I've not finished the API documentation. How important do you think it is that the documentation is more complete before release?

**Comment by mateogianolio** [comment]
I think for now the readme covers it it pretty well. I added links to Wikipedia articles which describe the operations in more detail and links to all method descriptions. I think we should release now and leave the documentation and benchmarks as a work in progress that we continue improving on in subsequent ```2.x.x``` updates.

**Comment by metabench** [comment]
If documentation changes I'm doubtful it means incrementing the version number.

I think if the benchmarks change then the version number will change. I also think that the existing benchmarks should be left alone as much as possible so the comparisons between versions are stable.

I looked at the documentation and it does make clear the `2.0.0` API so I think it's good to release it.

**Comment by mateogianolio** [comment]
OK, I'll merge and publish it to ```npm```.

**Comment by mateogianolio** [comment]
Great work by the way! This library has potential and I'm glad you decided to join me in developing it.

**Comment by metabench** [comment]
I'm glad to have helped.

**Pull request merged**
