### PR TITLE
refactor: add some improvements

### PR DESCRIPTION
**Pull request by Beraliv**
* replace unused variable with `_`
* `throw` stops running the code in a function, so don't need to use `else` then
* `||`-operator is working wrong when falsy values go, so better replace them with `!=`-operator (as it's not strict and only `undefined` and `null` are usable there)
* better put conditions out of `for` loop to not evaluating them over and over for no need
* `+0.0` and `0.0` are exactly same values
* `[].slice` is shorter than `Array.prototype.slice`. Moreover, it converts `arguments` to an `array` from the beginning (index `0`) by default, so you don't need to set it manually
* sometimes saving values to variables can take more time, it might be ambiguous
* `Math.max` and `Math.min` work longer than your own implementation
* `check` function can take `any` values now with `Number.isFinite`

### CODE REVIEW

**Comment by Beraliv** [comment]
@mateogianolio please have a look at it

The PR fixes [Issue#113](https://github.com/mateogianolio/vectorious/issues/113) about `deviation` and `mean` default values

**Comment by mateogianolio** [comment]
Hey @Beraliv! Looks great, I’m on my phone right now so I'll have a look at it and merge tomorrow. Thank you so much for your contribution!

**Comment by Beraliv** [comment]
There are some problems with ES6 features in `nyc` dependency in Travis CI
Do you know something about it? @mateogianolio

**Comment by Beraliv** [comment]
There are some problems with `nyc`
Have a look at it, @mateogianolio

**Comment by mateogianolio** [comment]
Seems like nyc requires node >= 6. I updated node version in travis to 6.9.0, let's see if it works.

**Comment by mateogianolio** [comment]
Yep, that was it! Great job 👍

**Pull request merged**
