### PR TITLE
CBLAS C++ bindings

### PR DESCRIPTION
**Pull request by mateogianolio**
Opening this PR so we can track changes. Works with both test and benchmark suites. Breaking changes are that prototype methods do not return a new `Vector`/`Matrix`, instead operations (`add`, `scale` etc) edit the current `Vector`/`Matrix` in-place for improved performance.

### CODE REVIEW

**Comment by waylonflinn** [comment]
"travis please", I imagine you saying this like you would say a certain expletive starting with "b"
:smile: :rocket:

**Comment by waylonflinn** [comment]
This is awesome, Mateo. I'm going to start a branch for GPU support, too.
What's the 'opt` prefix for?

**Comment by mateogianolio** [comment]
Haha, exactly. Thanks! `opt` is for optimization.

**Comment by mateogianolio** [comment]
Is it possible to include nblas only if the build is successful, otherwise make it "fall back" into using default behaviour?

Also, here are outputs from the new `bigmatrix.js` and `bigvector.js` benchmarks:

```
data = randomArray(4096, 4096)
a = Matrix(data)
b = Matrix(data).scale(2)

Matrix.identity(4096) x 11.25 ops/sec ±4.05% (33 runs sampled)
Matrix.magic(4096) x 2.63 ops/sec ±1.01% (11 runs sampled)
Matrix.zeros(4096, 4096) x 11.32 ops/sec ±0.96% (32 runs sampled)
Matrix.ones(4096, 4096) x 11.07 ops/sec ±0.89% (32 runs sampled)
Matrix.augment(a, b) x 3.90 ops/sec ±0.73% (14 runs sampled)
a.add(b) x 40.34 ops/sec ±0.44% (54 runs sampled)
a.subtract(b) x 39.72 ops/sec ±0.48% (53 runs sampled)
a.scale(Math.random()) x 62.61 ops/sec ±0.43% (66 runs sampled)
a.multiply(b) x 0.39 ops/sec ±4.62% (5 runs sampled)
a.transpose() x 3.35 ops/sec ±0.76% (13 runs sampled)
a.diag() x 26,803 ops/sec ±2.84% (85 runs sampled)
a.trace() x 19,368 ops/sec ±2.62% (82 runs sampled)

Done!
data = randomArray(262144)
a = Vector.ones(data)
b = Vector.ones(data).scale(2)

Vector.zeros(262144) x 643 ops/sec ±7.11% (73 runs sampled)
Vector.ones(262144) x 631 ops/sec ±7.37% (70 runs sampled)
Vector.range(0, 262144) x 234 ops/sec ±5.07% (78 runs sampled)
Vector.combine(a, b) x 49.98 ops/sec ±4.88% (66 runs sampled)
a.add(b) x 3,493 ops/sec ±0.42% (92 runs sampled)
a.subtract(b) x 3,446 ops/sec ±0.69% (94 runs sampled)
a.scale(Math.random()) x 9,500 ops/sec ±4.97% (93 runs sampled)
a.normalize() x 9,013 ops/sec ±4.15% (87 runs sampled)
a.dot(b) x 3,876 ops/sec ±6.95% (70 runs sampled)
a.magnitude() x 9,754,164 ops/sec ±3.12% (89 runs sampled)
a.angle(b) x 2,829 ops/sec ±1.83% (90 runs sampled)
a.project(b) x 2,298 ops/sec ±2.41% (84 runs sampled)
```

**Comment by waylonflinn** [comment]
I think you'd need some kind of optional `require`. If `nblas` is installed it will require it. If not you'll get an empty object back.
I think you can wrap the `nblas` require in a `try...catch`. Or use something like this: [optional](https://www.npmjs.com/package/optional)

**Comment by mateogianolio** [comment]
Breaking changes: `vector.buffer` member removed, `vector.values` changed to `vector.data`, removed memcpy dependency by rewriting `Vector.combine()` and `Vector.push()`

**Comment by mateogianolio** [comment]
Yes, for performance reasons: https://en.wikipedia.org/wiki/In-place_matrix_transposition

**Comment by mateogianolio** [comment]
Working on generating a C++ [LAPACK](https://software.intel.com/en-us/node/520866) binding for node as well.

**Comment by mateogianolio** [comment]
[Code Climate](https://codeclimate.com/github/mateogianolio/vectorious) [Test Coverage](https://codeclimate.com/github/mateogianolio/vectorious/coverage)

**Comment by mateogianolio** [comment]
Trying to compare numpy and vectorious performance.

```bash
$ python -m timeit -s "import numpy as np; a = np.random.rand(262144); b = np.random.rand(262144)" "np.add(a, b)"
1000 loops, best of 3: 441 usec per loop

$ python -m timeit -s "import numpy as np; a = np.random.rand(262144); b = np.random.rand(262144)" "np.dot(a, b)"
10000 loops, best of 3: 182 usec per loop

$ python -m timeit -s "import numpy as np; a = np.random.rand(262144); b = np.random.rand(262144)" "a * np.random.random_sample()"
1000 loops, best of 3: 289 usec per loop
```

Converted to ops/sec, operations are for two vectors of size `262144`:

**Numpy**

- **numpy addition**: 2,267 ops/sec
- **numpy dot**: 5,494 ops/sec
- **numpy scale**:  3,460 ops/sec

**Vectorious**

- **vectorious add**: 3,493 ops/sec
- **vectorious dot**: 3,876 ops/sec
- **vectorious scale**: 9,500 ops/sec

**Comment by mateogianolio** [comment]
We could attach a `tmp` – or whatever we want to call it – variable (TypedArray) of the same size and type as the `Vector`/`Matrix` to the prototype.

Like
```javascript
// ... in constructor
this.tmp = new this.type(this.length); // for vector
this.tmp = new this.type(this.shape[0] * this.shape[1]); // for matrix

// ... in add
for (var i = 0; i < this.length; i++)
  this.tmp[i] = this.data[i] + vector.data[i];

// ... or with nBLAS
nblas.copy(this.data, this.tmp); // copy data to tmp
nblas.axpy(vector.data, this.tmp); // add data with tmp and put result in tmp
```

Then we have the original vector/matrix (`this.data`) and the result (`this.tmp`) accessible. Just a thought, haven't really thought it through yet.

**Comment by mateogianolio** [comment]
@waylonflinn @metabench check out https://github.com/codeforscience/webdata

**Comment by waylonflinn** [comment]
@mateogianolio thanks!

**Comment by mateogianolio** [comment]
How's this for a wrapper?

```javascript
function vector(f, ...args) {
  var fArgs = f
    .toString()
    .replace(/[\[\( \)\]]/g, '')
    .split('=>');

  var op = fArgs.shift();
  if (!(op in vectorious.Vector))
    return f(...args);

  fArgs = fArgs[0]
    .split(',')
    .map(num);

  return vectorious.Vector[op](...fArgs);
}
```

```javascript
var a = vector(range => (0, 5)),
    b = vector(ones => 5).scale(10),
    c = vector(zeros => 2);

console.log('a: ' + a);
console.log('b: ' + b);
console.log('c: ' + c + '\n');

// custom in-place operation
vector(a => a.data[0] = 5, a);

console.log('a: ' + a);
```

```
a: [0, 1, 2, 3, 4]
b: [10, 10, 10, 10, 10]
c: [0, 0]

a: [5, 1, 2, 3, 4]
b: [10, 10, 10, 10, 10]
```

**Comment by mateogianolio** [comment]
After thinking about it for a while, I think the best way to move forward is to add a `result` argument to all prototype functions. If the extra argument is supplied perform the operation in-place, otherwise return a copy.

**Pull request merged**
