### PR TITLE
V3 matrix optimization

### PR DESCRIPTION
**Pull request by waylonflinn**
Still a lot to do here, but I wanted to open the PR in case you guys were curious.

Purpose of these changes is to optimize matrix multiplies (and other operations) by moving to a single TypedArray, instead of the row vector format. These changes speed matrix multiply up by 10x for me, and likely give significant speed improvements for some other operations.

Some changes require node >= 4.0 (specifically the `ones` and `zeros` methods).

### CODE REVIEW

**Comment by mateogianolio** [comment]
I have only just skimmed it through, but it looks good. Great job. Node `>=4.0` is a reasonable requirement.

One question though, you seem to have picked `Float64Array` as the standard Matrix `TypedArray`, but in previous versions this could be picked manually (default being `Float64Array`):

```javascript
> var v = require('vectorious');
> new v.Vector(Uint8Array, 1, 2, 3);
Vector {
  type: [Function: Uint8Array],
  length: 3,
  buffer: ArrayBuffer {},
  values: Uint8Array { '0': 1, '1': 2, '2': 3 } }

> new v.Matrix(Uint8Array, [[1, 2], [3, 4]]);
Matrix {
  rows:
   [ Vector {
       type: [Function: Uint8Array],
       length: 2,
       buffer: ArrayBuffer {},
       values: [Object] },
     Vector {
       type: [Function: Uint8Array],
       length: 2,
       buffer: ArrayBuffer {},
       values: [Object] } ],
  type: [Function: Uint8Array] }

> new v.Matrix(new v.Vector(Uint8Array, 1, 2, 3));
Matrix {
  rows:
   [ Vector {
       type: [Function: Uint8Array],
       length: 3,
       buffer: ArrayBuffer {},
       values: [Object] } ],
  type: [Function: Float64Array] }
```

In this case `Uint8Array` is faster than `Float64Array`. By the way, just noticed the last example infers the wrong Matrix type.

**Comment by waylonflinn** [comment]
Thanks for checking it out so quickly. 



I definitely think preserving other array types is a good idea. My approach is to get something optimized working, then generalize from there.






Great feedback! Let me know what else you find.



—

**Comment by mateogianolio** [comment]
All right, sounds good!

**Comment by metabench** [comment]
@waylonflinn, @mateogianolio Does this implementation using the single Typed Array support 'A generalized n-dimensional matrix'?

Also, would you agree that this changes the API in a breaking way, so should get a new version number, and also change tests so that they interact with the library differently?

**Comment by mateogianolio** [comment]
@metabench I'm not going to merge this until all tests pass, but I think having the pull request up is a motivation in itself to progress with the library.

**Comment by metabench** [comment]
@mateogianolio First of all I am not familiar with the code in this push request. Judging by what is being proposed, it changes the API used to interact with the vectorious library. I could have misjudged that, and I'd like clarification if possible.

If it is the case that vectorious is going to be called differently once this change has been made, it would be necessary to change the tests to support the new API (such as calling constructors differently).

**Comment by waylonflinn** [comment]
@metabench I'm hoping to keep breaking changes to a minimum (though the constructor is different right now). I would say the changes are big enough that a new version is in order.

It doesn't quite generalize to n-dimensional arrays (tensors), but it lays the foundations for it. I'm thinking about taking this work and creating a new library that does that, possibly incorporating the GPU code, too.

There's been a lot of interest in running Neural Networks in javascript recently, and fast four dimensional tensors that run on a GPU would help that a lot.

**Comment by metabench** [comment]
@waylonflinn I am also very interested in using GPU acceleration, but through OpenCL. I have already done some experiments with OpenCL, and got some promising results so far (see https://github.com/metabench/opencljs-experiments).

GPU acceleration is a very promising direction to take this library. I am also glad that you have come up with a suggestion on how to greatly speed up the matrix side of things, and have implemented some/much of it too.

I would be interested in using this for neural networks, as well as image processing.

Having the same API for GPU accelerated vectors and matrices on both the client and server would be very useful.

**Comment by mateogianolio** [comment]
@waylonflinn @metabench Good to know that we are all interested in neural networks :)

**Comment by waylonflinn** [comment]
:+1:

**Comment by waylonflinn** [comment]
@metabench cool add-on. 

This also looks promising for GPU support in the short term: [WebCLGL](https://github.com/stormcolor/webclgl)

Perhaps combined with this, for node [headless-gl](https://github.com/stackgl/headless-gl)

**Comment by waylonflinn** [comment]
Almost done. I'm using a shallow implementation for Transpose (no moving of data) and it's not quite complete.

**Comment by mateogianolio** [comment]
Benchmarks (`npm run benchmark`) for `master` branch:

```
Matrix.identity(128) x 4,423 ops/sec ±2.70% (83 runs sampled)
Matrix.magic(128) x 1,311 ops/sec ±4.92% (62 runs sampled)
Matrix.zeros(128, 128) x 4,316 ops/sec ±3.12% (76 runs sampled)
Matrix.ones(128, 128) x 4,352 ops/sec ±2.92% (68 runs sampled)
Matrix.augment(a, b) x 686 ops/sec ±3.64% (82 runs sampled)
a.add(b) x 3,814 ops/sec ±5.06% (68 runs sampled)
a.subtract(b) x 3,697 ops/sec ±5.16% (63 runs sampled)
a.scale(Math.random()) x 3,863 ops/sec ±4.95% (66 runs sampled)
a.multiply(b) x 33.53 ops/sec ±0.95% (59 runs sampled)
a.transpose() x 2,354 ops/sec ±4.82% (80 runs sampled)
a.gauss() x 900 ops/sec ±4.84% (76 runs sampled)
a.diag() x 2,635 ops/sec ±3.89% (74 runs sampled)
a.trace() x 2,655 ops/sec ±3.80% (76 runs sampled)
```

this PR:

```
Matrix.identity(128) x 10,319 ops/sec ±5.52% (84 runs sampled)
Matrix.magic(128) x 2,237 ops/sec ±2.39% (94 runs sampled)
Matrix.zeros(128, 128) x 10,346 ops/sec ±5.59% (83 runs sampled)
Matrix.ones(128, 128) x 10,333 ops/sec ±5.79% (83 runs sampled)
Matrix.augment(a, b) x 3,667 ops/sec ±5.20% (87 runs sampled)
a.add(b) x 10,163 ops/sec ±5.76% (85 runs sampled)
a.subtract(b) x 10,001 ops/sec ±5.99% (81 runs sampled)
a.scale(Math.random()) x 10,668 ops/sec ±6.13% (77 runs sampled)
a.multiply(b) x 215 ops/sec ±1.74% (84 runs sampled)
a.transpose() x 12,677 ops/sec ±4.20% (77 runs sampled)
a.gauss() x 3,303 ops/sec ±1.93% (87 runs sampled)
a.diag() x 2,840 ops/sec ±3.67% (73 runs sampled)
a.trace() x 2,834 ops/sec ±3.84% (72 runs sampled)
```

**Comment by waylonflinn** [comment]
Not bad for a day's work. I'll check out the benchmarks tomorrow and see why it's not quite 10x.

:+1:

**Comment by mateogianolio** [comment]
:+1:

**Comment by mateogianolio** [comment]
@waylonflinn @metabench Ready for release?

**Comment by metabench** [comment]
Does it support tensors?

If not, it would be best to either hold off on pushing this code until tensor support is there, or we clarify that Vectorious won't support tensors for the time being in the readme, and have a good description for what it actually does.

**Comment by mateogianolio** [comment]
Maybe we could change the description to "High performance linear algebra library in javascript" which would remove the confusion around dimensionality and still allow for the introduction of tensors in the future.

**Comment by waylonflinn** [comment]
Still needs support for more than just Float64Array, if you guys want to tackle that, it would be greatly appreciated. Any volunteers?

I also think we should add a benchmark comparison (maybe as an image) with the other matrix libraries to the `README`. I'm working on creating that, based on this: [Matrix Benchmark](http://waylonflinn.github.io/js-matrix-benchmarks/matrix_benchmark.html)

**Comment by mateogianolio** [comment]
I'll do it

**Comment by waylonflinn** [comment]
:+1:

**Comment by waylonflinn** [comment]
Updating the README with the new description and merging.

**Comment by waylonflinn** [comment]
Running some tests in the browser, I've noticed that some more of the TypedArray methods need a polyfill. Created Issue #41 to track this.

**Comment by waylonflinn** [comment]
Hope I didn't jump the gun on this merge. Wasn't sure how you guys wanted to proceed.

**Comment by mateogianolio** [comment]
I've added support for all typed arrays on a local copy of this branch, how do I push them?

**Comment by waylonflinn** [comment]
:+1:

**Pull request merged**
